### ISSUE TITLE
关于js代码方面的,我现在调用

### ISSUE THREAD

**Issue by yuwade** [jiayisheji/blog#25]
大神我有个问题,
我现在使用的lodash.js
只是使用了里面的几个方法, 
我要做一个单页面的html给客户
客户在无网情况下使用的
我看着js的方法都是调用层次太多,
有没有什么好的方法或者工具直接提取这个方法的所有实现代码
谢谢大神指点

**Comment by jiayisheji** [comment]
@yuwade 使用`npm install lodash`，引入时候不要把它全部导入进去`import * as _ from 'lodash';`

要这样，需要那些导入那些

`import { isFunction, isString, find, compact, last, first, cloneDeep } from 'lodash';`

配合webpack摇树打包，会自动帮你剔除无用的代码。

还有lodash也可以安装单个包，比如深拷贝`npm i --save lodash.clonedeep`

用的时候`import * as clonedeep from 'lodash.clonedeep';`
